[package]
name = "stun"
version = "0.1.0"
edition = "2024"

[dependencies]
stunclient = "=0.4.2"
tokio = { version = "1.49.0", features = ["full"] }
types ={ path = "../types"}
uuid = {version = "1.21.0",features = ["v4"]}